name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created || steps.release.outputs.releases_created }}
      release_id: ${{ steps.release.outputs.release_id || steps.release.outputs['--release_id'] }}
      tag_name: ${{ steps.release.outputs.tag_name || steps.release.outputs['--tag_name'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release

  build-tauri:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: install frontend dependencies
        run: pnpm install

      - name: setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: app
          tauriScript: pnpm tauri
          releaseId: ${{ needs.release-please.outputs.release_id }}
          tagName: ${{ needs.release-please.outputs.tag_name }}
